services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DOCKER_COMPOSE_ENABLED: "false"
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/traffic
      SPRING_DATASOURCE_USERNAME: traffic
      SPRING_DATASOURCE_PASSWORD: traffic
    depends_on:
      postgres:
        condition: service_healthy
  
